[package]
name = "flux-serverless"
version = "0.1.0"
edition = "2021"

[features]
default = []

[dependencies]
image = "0.25.2"
reqwest = "0.12.6"
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.125"